### ISSUE TITLE
Add new github actions

### ISSUE THREAD

**Issue by nmasahiro** [st-tech/zr-obp#79]
## Motivation
This issue summarizes the github actions that we plan to introduce in the future.

## TODOs
- [ ] [flake8](https://github.com/PyCQA/flake8) (or [hacking](https://github.com/openstack/hacking))
- [ ] [mypy](https://github.com/python/mypy)
- [ ] [isort](https://github.com/PyCQA/isort)

**Comment by nmasahiro** [comment]
This can be a good candidate:
https://github.com/pfnet/pysen
